version: '3'
services:
  app:
    build: .
    ports:
      - "4000:4000"
    links:
        - mongodb
    depends_on:
        - mongodb

  mongodb:
    build:
      context: ./docker-scripts
      dockerfile: MongoDockerfile
    ports:
        - 27017:27017

    volumes:
      - db-data:/data/db      

volumes:
  db-data:

